services:

  mlops:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-mlops-platform
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    depends_on:
      - mlflow-ui
    networks:
      - ai-mlops-network

  mlflow-ui:
    image: python:3.11-slim
    container_name: mlflow-ui
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install mlflow && mlflow ui --backend-store-uri file:/app/mlruns --host 0.0.0.0 --port 5000"
    ports:
      - "5001:5000"
    networks:
      - ai-mlops-network

networks:
  ai-mlops-network:
    driver: bridge

