mode: prod

dev:
  path: data/raw-data/sample_1k.csv
  output_path: s3a://my-mlops-processed-data/dev/
  local_output_path: data/processed/dev/

prod:
  path: data/raw-data/sample_100k.csv
  output_path: s3a://my-mlops-processed-data/prod/
  local_output_path: data/processed/prod/

format: csv

s3_path: s3a://my-mlops-raw-data/
s3_output_path: s3a://my-mlops-processed-data/

aws:
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  region: eu-central-1
  
checkpoint_location: s3a://my-mlops-checkpoints/ingest_job/

# --- Se usi GCP:
#gcp:
#  project_id: my-gcp-project
#  keyfile_json: ${GOOGLE_APPLICATION_CREDENTIALS}
#  bucket: your-gcp-bucket

# --- Se usi Azure:
#azure:
#  storage_account: yourStorageAccount
#  container: rawdata
#  tenant_id: ${AZURE_TENANT_ID}
#  client_id: ${AZURE_CLIENT_ID}
#  client_secret: ${AZURE_CLIENT_SECRET}