version: '3'
services:
  mlflow:
    build:
      context: ..
      dockerfile: mlops/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
