name: CI/CD Pipeline

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  PYTHON_VERSION: '3.11'
  REGISTRY: ghcr.io/impesud

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      models_changed: ${{ steps.check_changes.outputs.models_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip setuptools
          pip install -r requirements.txt
          pip install pre-commit

      - name: Debug environment
        run: |
          . venv/bin/activate
          python --version
          pip freeze

      - name: Run pre-commit checks
        run: |
          . venv/bin/activate
          pre-commit run --all-files

      - name: Prepare MLflow directory
        if: github.event_name != 'pull_request'
        run: mkdir -p mlruns

      - name: Run pipeline logic
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          . venv/bin/activate
          chmod -R +x scripts/
          BRANCH=$(echo "${GITHUB_REF##*/}")
          if [[ "$BRANCH" == "main" ]]; then
            make ingest-prod-local
            make process-prod-local
            if [[ "${{ github.event_name }}" != "pull_request" ]]; then
              make train-prod-local
            fi
          else
            make ingest-dev-local
            make process-dev-local
            if [[ "${{ github.event_name }}" != "pull_request" ]]; then
              make train-dev-local
            fi
          fi

      - name: Run unit tests
        run: |
          . venv/bin/activate
          chmod -R +x tests/
          BRANCH=$(echo "${GITHUB_REF##*/}")
          pytest tests/

      - name: Upload MLflow model artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: mlruns/**/artifacts/model/

      - name: Detect changes in model-related directories
        id: check_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            models:
              - 'models/**'
              - 'data_processing/**'
              - 'configs/**'

  docker-build-and-push:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REGISTRY }}/ai-mlops-project:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  model-smoke-test:
    needs: build-and-test
    if: needs.build-and-test.outputs.models_changed == 'true' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pip install mlflow pandas

      - uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: mlruns

      - run: |
          nohup mlflow models serve -m mlruns/**/model --no-conda --port 1234 &
          sleep 10

      - run: |
          curl -X POST http://127.0.0.1:1234/invocations \
            -H 'Content-Type: application/json' \
            -d '{"dataframe_records":[{"value":42.0,"hour":12.0,"day_of_week":3.0,"month":6.0}]}' || true

      - run: echo "✅ Model smoke test completed"

  semantic-release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/github

      - name: Run semantic-release with PAT
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: semantic-release




