name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools
          pip install -r requirements.txt
          pip install pytest

      - name: Prepara directory per MLflow
        run: mkdir -p mlruns

      - name: Set environment variable for MLflow
        run: echo "MLFLOW_TRACKING_URI=file:./mlruns" >> $GITHUB_ENV

      - name: Run pipeline (data ingest + training)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          source venv/bin/activate
          python scripts/pipeline.py
      
      - name: List artifacts
        run: find mlruns

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: |
            mlruns/**/artifacts/model

      - name: Build Docker image
        run: |
          docker build -f mlops/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/ai-mlops-project:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/ai-mlops-project:latest

  deploy-model:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies for MLflow
        run: pip install mlflow pandas

      - name: Download trained model artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: mlruns  

      - name: Check model structure
        run: ls -R mlruns/

      - name: Get latest model path
        id: model-path
        run: |
          MODEL_PATH=$(python scripts/get_latest_model_path.py)
          echo "MODEL_PATH=$MODEL_PATH"
          echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV

      - name: Serve model locally
        run: |
          nohup mlflow models serve -m $MODEL_PATH --no-conda --port 1234 &
          sleep 10

      - name: Test inference endpoint
        run: |
          curl -X POST http://127.0.0.1:1234/invocations \
            -H 'Content-Type: application/json' \
            -d '{"dataframe_records":[{"value":42.0, "timestamp":1684012800}]}'

      - name: Deployment complete
        run: echo "✅ Model deployed and tested successfully"

