# models/config.yaml

# Percorso S3 dove Spark ha scritto i parquet
input_path: s3a://my-mlops-processed-data/

# Parametri di training
test_size: 0.2
random_seed: 42

# Parametri del modello
model_params:
  n_estimators: 100
  max_depth: 10

#Parametri del Generative AI
generative_ai:
  enabled: true
  prompt: "Analisi dei dati"
  output_path: "report.txt"