mode: prod

dev:
  input_path: s3a://my-mlops-processed-data/dev/
  test_size: 0.2
  random_seed: 42
  model_params:
    n_estimators: 100
    max_depth: 10
  generative_ai:
    enabled: true
    prompt: "Analisi dei dati (DEV)"
    output_path: "report_dev.txt"

prod:
  input_path: s3a://my-mlops-processed-data/prod/
  test_size: 0.2
  random_seed: 42
  model_params:
    n_estimators: 200
    max_depth: 15
  generative_ai:
    enabled: true
    prompt: "Analisi dettagliata dei dati"
    output_path: "report_prod.txt"
