input_path: "s3a://my-mlops-processed-data/prod/"
test_size: 0.2
random_seed: 42
features:
  - value
  - hour
  - day_of_week
  - day_of_month
  - week_of_year
  - month
  - is_weekend
  - total_value
  - total_events
  - purchase_events
  - purchase_ratio
  - avg_events_per_day
  - recency_days
  - rolling_purchase_7d
  - rolling_value_7d
  - rolling_events_7d
  - rolling_avg_value_7d
  - user_segment
model_params:
  maxIter: 40
  maxDepth: 10
  stepSize: 1
  subsamplingRate: 0.8
  minInstancesPerNode: 5
  minInfoGain: 0.01
grid:
  maxIter: [40, 60]
  maxDepth: [5, 10]
  stepSize: [0.05, 0.1]
  subsamplingRate: [0.7, 1.0]
  #minInstancesPerNode: [2, 5]
  minInfoGain: [0.0, 0.01]
numFolds: 2
parallelism: 2

